"""init

Revision ID: 871355399d14
Revises: 
Create Date: 2021-01-10 11:58:18.851321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871355399d14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
